name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  plugins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Plugin Validation
        run: python3 scripts/validate-plugins.py
